version: 2.1

jobs:
  lint-client:
    executor: client-node-executor
    steps:
      - checkout
      - install-client-node-dependencies
      - run:
          command: yarn run prettylint "src/**/*.[jt]s?(x)"
          working_directory: ~/project/web_client

  build-client:
    executor: client-node-executor
    steps:
      - checkout
      - install-client-node-dependencies
      - run:
          command: yarn build
          working_directory: ~/project/web_client
      - persist_to_workspace:
          root: ~/project/web_client
          paths:
            - build

  cypress-tests:
    executor: cypress-executor
    steps:
      - checkout
      - install-client-node-dependencies
      - attach_workspace:
          at: ~/project/web_client
      - run:
          name: Run server
          working_directory: ~/project/web_client
          command: yarn run serve -s build
          background: true
      - run:
          name: Run cypress tests
          command: >-
            yarn run cypress run --reporter junit
            --reporter-options "mochaFile=test-results/cypress/results.[hash].xml"
          working_directory: ~/project/web_client
      - store_test_results:
          path: ~/project/web_client/test-results
      - store_artifacts:
          path: ~/project/web_client/cypress/videos

workflows:
  build:
    jobs:
      - lint-client
      - build-client
      - cypress-tests:
          requires:
            - build-client

executors:
  client-node-executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/project
  cypress-executor:
    docker:
      - image: cypress/base:10
    working_directory: ~/project

commands:
  install-client-node-dependencies:
    steps:
      - restore_cache:
          keys:
            - node-cache-{{ checksum "~/project/web_client/yarn.lock" }}
      - run:
          command: yarn install
          working_directory: ~/project/web_client
      - save_cache:
          key: node-cache-{{ checksum "~/project/web_client/yarn.lock" }}
          paths: node_modules
